using System;
using System.Collections;
using GeneXus.Utils;
using GeneXus.Resources;
using GeneXus.Application;
using GeneXus.Metadata;
using GeneXus.Cryptography;
using GeneXus.Data.ADO;
using GeneXus.Data.NTier;
using GeneXus.Data.NTier.ADO;
using GeneXus.XML;
using GeneXus.Search;
using GeneXus.Encryption;
using GeneXus.Http.Client;
using System.Xml.Serialization;
namespace GeneXus.Programs {
   public class GxFullTextSearchReindexer
   {
      public static int Reindex( IGxContext context )
      {
         GxSilentTrnSdt obj;
         IGxSilentTrn trn;
         bool result;
         obj = new GeneXus.Programs.wwpbaseobjects.SdtUserCustomizations(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtPais(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtOperador(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtMedidaSeguranca(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtCompartInterno(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtSetorInterno(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtFonteRetencao(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtCompartTercExterno(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtInformacao(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtHipoteseTratamento(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtEnvolvidosColeta(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDicionarioCompartTercExt(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtTooltip(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtParametro(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDicionarioPais(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDocImagem(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDocumento(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDocAnexo(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDocOperador(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDocDicionario(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtCategoria(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtSubProcesso(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtEncarregado(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtTipoDado(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtControlador(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtFerramentaColeta(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtFrequenciaTratamento(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtAbrangenciaGeografica(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtTipoDescarte(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtTempoRetencao(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDocEnvolvidosColeta(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDocSetorInterno(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtProcesso(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtPersona(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDocCompartInterno(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtRevisaoLog(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtAreaResponsavel(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDocFonteRetencao(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         obj = new SdtDocMedidaSeguranca(context);
         trn = obj.getTransaction();
         result = trn.Reindex();
         return 1 ;
      }

   }

}
